/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlefinanceiro;

import java.awt.Color;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class meuControle extends javax.swing.JFrame {

    /**
     * Creates new form meuControle
     */
    public meuControle() {
        initComponents();
    }

    double credito, debito, total = 0;
    
    NumberFormat formatacao;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLblcredito = new javax.swing.JLabel();
        jLbldebito = new javax.swing.JLabel();
        jLbltotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTxtdesc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCmbtipo = new javax.swing.JComboBox<>();
        jTxtvalor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCmbcategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTxtdata = new javax.swing.JTextField();
        jBtnadd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jBtnremover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROLE FINANCEIRO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 20, 510, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLblcredito.setBackground(new java.awt.Color(0, 255, 0));
        jLblcredito.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblcredito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblcredito.setText("R$00,00");
        jLblcredito.setOpaque(true);
        jPanel2.add(jLblcredito);
        jLblcredito.setBounds(50, 30, 240, 50);

        jLbldebito.setBackground(new java.awt.Color(255, 51, 51));
        jLbldebito.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLbldebito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbldebito.setText("R$00,00");
        jLbldebito.setOpaque(true);
        jPanel2.add(jLbldebito);
        jLbldebito.setBounds(330, 30, 240, 50);

        jLbltotal.setBackground(new java.awt.Color(0, 0, 255));
        jLbltotal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbltotal.setText("R$00,00");
        jLbltotal.setOpaque(true);
        jPanel2.add(jLbltotal);
        jLbltotal.setBounds(600, 30, 240, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 900, 110);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Descrição");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 20, 350, 10);
        jPanel3.add(jTxtdesc);
        jTxtdesc.setBounds(12, 37, 362, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Tipo");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 70, 200, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Valor");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(260, 70, 80, 17);

        jCmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Tipo", "Crédito", "Despesa" }));
        jPanel3.add(jCmbtipo);
        jCmbtipo.setBounds(20, 90, 200, 20);
        jPanel3.add(jTxtvalor);
        jTxtvalor.setBounds(260, 90, 190, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Categoria ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 120, 200, 17);

        jCmbcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Categoria", "Receita", "Lazer", "Alimentação", "Saúde", "Moradia", "Estudos" }));
        jPanel3.add(jCmbcategoria);
        jCmbcategoria.setBounds(20, 140, 200, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Data");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(260, 120, 190, 17);
        jPanel3.add(jTxtdata);
        jTxtdata.setBounds(260, 140, 190, 20);

        jBtnadd.setBackground(new java.awt.Color(0, 0, 0));
        jBtnadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBtnadd.setText("Adicionar");
        jBtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnaddActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnadd);
        jBtnadd.setBounds(20, 180, 430, 25);

        jLabel10.setText("Últimos Lançamentos");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 210, 370, 14);

        jBtnremover.setBackground(new java.awt.Color(0, 0, 0));
        jBtnremover.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jBtnremover.setText("Remover");
        jBtnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnremoverActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnremover);
        jBtnremover.setBounds(20, 380, 430, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Tipo", "Valor", "Categoria", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(22, 232, 430, 130);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 180, 470, 430);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(470, 180, 430, 210);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(470, 390, 430, 220);

        setBounds(0, 0, 912, 655);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnaddActionPerformed
        // TODO add your handling code here:
        
        //Variávies para receber os valores digitados
        String descricao, tipo, valor, categoria, data;
        //Formatação para apresentar o numero em R$
        formatacao = NumberFormat.getCurrencyInstance();

        if ("".equals(jTxtvalor.getText().trim())) {
            //Mostra mensagem 
            JOptionPane.showMessageDialog(null, "Favor informar o valor");
        } else {

            //Atribui os valores das caixas de texto e combobox para as respectivas 
            //variáveis 
            descricao = jTxtdesc.getText();
            tipo = jCmbtipo.getSelectedItem().toString();
            valor = jTxtvalor.getText();
            categoria = jCmbcategoria.getSelectedItem().toString();
            data = jTxtdata.getText();
            //  Verifica se o tipo selecionado é = a Crédito
            if ("Crédito".equals(tipo)) {
                //Soma os valores referentes a Crédito
                credito = credito + Double.parseDouble(valor);
                //Formata e apresenta o valor na jLabel
                jLblcredito.setText(formatacao.format(credito));
            }
            //  Verifica se o tipo selecionado é = Despesa
            if ("Despesa".equals(tipo)) {
                //Soma os valores referentes ao Debito
                debito = debito + Double.parseDouble(valor);
                //Formata e apresenta o valor na jLabel
                jLbldebito.setText(formatacao.format(debito));
            }

            //Faz o calculo do total 
            total = credito - debito;
            //Apresenta o valor total 
            jLbltotal.setText(formatacao.format(total));

            //Adiciona um nova linha no jTable
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.addRow(new Object[]{descricao, tipo, valor, categoria, data});
            
            if (total < 0)

{

jLbltotal.setBackground(Color.red);

}

if (total > 0)

{

jLbltotal.setBackground(Color.blue);

}
}
        grafico g1 = new grafico();
        g1.barra(credito, debito, jPanel4);
        g1.pizza(credito, debito, jPanel5);
        
    }//GEN-LAST:event_jBtnaddActionPerformed

    private void jBtnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnremoverActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        //Se foi seleciona alguma linha do jTable
        if (jTable1.getSelectedRow() >= 0) {
            int linha = jTable1.getSelectedRow();
            Object tipo = jTable1.getValueAt(linha, 1);
            Object valor = jTable1.getValueAt(linha, 2);
            if ("Crédito".equals(tipo)) {
                //Soma os valores referentes a Crédito
                credito = credito - Double.parseDouble(valor.toString());
                //Formata e apresenta o valor na jLabel
                jLblcredito.setText(formatacao.format(credito));                
            }
            if ("Despesa".equals(tipo)) {
                //Soma os valores referentes a Crédito
                debito = debito - Double.parseDouble(valor.toString());
                //Formata e apresenta o valor na jLabel
                jLbldebito.setText(formatacao.format(debito));
            }
            //Faz o calculo do total 
            total = credito - debito;
            //Apresenta o valor total 
            jLbltotal.setText(formatacao.format(total));

            //Re,ove a linha selecionada
            modelo.removeRow(jTable1.getSelectedRow());

            //senao
        } else {
            //Mostra mensagem 
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
        if (total < 0)

{

jLbltotal.setBackground(Color.red);

}

if (total > 0)

{

jLbltotal.setBackground(Color.blue);

}

        grafico g1 = new grafico();
        g1.barra(credito, debito, jPanel4);
        g1.pizza(credito, debito, jPanel5);
    }//GEN-LAST:event_jBtnremoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(meuControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(meuControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(meuControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(meuControle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new meuControle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnadd;
    private javax.swing.JButton jBtnremover;
    private javax.swing.JComboBox<String> jCmbcategoria;
    private javax.swing.JComboBox<String> jCmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblcredito;
    private javax.swing.JLabel jLbldebito;
    private javax.swing.JLabel jLbltotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtdata;
    private javax.swing.JTextField jTxtdesc;
    private javax.swing.JTextField jTxtvalor;
    // End of variables declaration//GEN-END:variables
}
